# Generated by Django 3.2.4 on 2022-02-24 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('firstname', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('lastname', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('name', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('reg_no', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('title', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('cover', models.ImageField(upload_to='')),
                ('genre', models.CharField(choices=[('MYSTERY', 'MYSTERY'), ('THRILLER', 'THRILLER'), ('HORROR', 'HORROR'), ('ROMANCE', 'ROMANCE'), ('FANTASY', 'FANTASY'), ('SCI-FI', 'SCIENCE FICTION'), ('CRIME', 'CRIME'), ('DRAMA', 'DRAMA')], max_length=15)),
                ('year_published', models.DateField()),
                ('size', models.IntegerField(blank=True, null=True)),
                ('author', models.ManyToManyField(to='core.Author')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.publisher')),
            ],
        ),
    ]
