# Generated by Django 3.2.4 on 2022-02-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='fild',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
