# Generated by Django 3.2.4 on 2022-02-28 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_book_fild'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='fild',
            new_name='description',
        ),
    ]
