# Generated by Django 3.2.4 on 2022-03-23 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_message_s'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Message_d',
        ),
    ]
