# Generated by Django 3.2.4 on 2022-03-23 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_message_d'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message_s',
            new_name='Message',
        ),
    ]
